const dummyData = [
    {
        "employer_name": "Patterned Learning AI",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ775Codjmht--KvEAjOrA-wSTocct7jOgsqnDZ&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "bBjNLBfvzUgAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Junior Python Developer",
        "job_apply_link": "https://www.linkedin.com/jobs/view/junior-python-developer-at-patterned-learning-ai-3639835509",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5576,
        "job_description": "REMOTE (US/Canada Residing people only, with work permit) Patterned Learning – Junior Python Developer, FULL-TIME, Salary $70K - $80K a year.\n\nAbout us: The Future of AI is Patterned, a stealth-mode technology startup. Top investors include Sequoia and Anderson Horowitz, founders from Google, DeepMind, and NASA and we’re hiring for almost everything!\n\nJob Description\n\nWe are seeking a talented and motivated Junior Python Developer to join our dynamic team. In this role, you will work closely with senior developers and other cross-functional teams to develop and maintain high-quality Python applications. As a Junior Python Developer, you will have the opportunity to learn and grow your skills while contributing to exciting projects.\n\nResponsibilities\n• Collaborate with senior developers to design and develop Python applications.\n• Write clean, efficient, and maintainable code that follows best practices.\n• Participate in code reviews and provide constructive feedback.\n• Debug and fix issues in existing codebase.\n• Assist in testing and quality assurance processes.\n• Stay updated with the latest trends and technologies in Python development.\n\nRequirements\n• Bachelor's degree in Computer Science, Software Engineering, or a related field.\n• Strong knowledge of Python programming language.\n• Familiarity with web frameworks such as Django or Flask.\n• Experience with version control systems, preferably Git.\n• Basic understanding of front-end technologies (HTML, CSS, JavaScript).\n• Good problem-solving and analytical skills.\n• Excellent communication and teamwork abilities.\n• Self-motivated and eager to learn.\n\nNice To Have\n• Experience with database systems such as MySQL, PostgreSQL, or MongoDB.\n• Knowledge of RESTful APIs and integration.\n• Familiarity with cloud platforms such as AWS or Azure.\n• Understanding of agile development methodologies.\n\nSpecial Benefits You Will Love\n• Flexible vacation, paid holidays, and paid sick days\n• 401(k) with up to 2% employer match\n• Health, vision, and dental insurance\n\nSchedule: 8 hour shift, Monday to Friday , Time: Flexible, Job Type: Full-time",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1687187052,
        "job_posted_at_datetime_utc": "2023-06-19T15:04:12.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": [
            "paid_time_off",
            "retirement_savings",
            "dental_coverage",
            "health_insurance"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=bBjNLBfvzUgAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-12-16T15:04:13.000Z",
        "job_offer_expiration_timestamp": 1702739053,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Bachelor's degree in Computer Science, Software Engineering, or a related field",
                "Strong knowledge of Python programming language",
                "Familiarity with web frameworks such as Django or Flask",
                "Experience with version control systems, preferably Git",
                "Basic understanding of front-end technologies (HTML, CSS, JavaScript)",
                "Good problem-solving and analytical skills",
                "Excellent communication and teamwork abilities",
                "Self-motivated and eager to learn",
                "Experience with database systems such as MySQL, PostgreSQL, or MongoDB",
                "Knowledge of RESTful APIs and integration",
                "Familiarity with cloud platforms such as AWS or Azure",
                "Understanding of agile development methodologies"
            ],
            "Responsibilities": [
                "In this role, you will work closely with senior developers and other cross-functional teams to develop and maintain high-quality Python applications",
                "As a Junior Python Developer, you will have the opportunity to learn and grow your skills while contributing to exciting projects",
                "Collaborate with senior developers to design and develop Python applications",
                "Write clean, efficient, and maintainable code that follows best practices",
                "Participate in code reviews and provide constructive feedback",
                "Debug and fix issues in existing codebase",
                "Assist in testing and quality assurance processes",
                "Stay updated with the latest trends and technologies in Python development"
            ],
            "Benefits": [
                "REMOTE (US/Canada Residing people only, with work permit) Patterned Learning – Junior Python Developer, FULL-TIME, Salary $70K - $80K a year",
                "Special Benefits You Will Love",
                "Flexible vacation, paid holidays, and paid sick days",
                "401(k) with up to 2% employer match",
                "Health, vision, and dental insurance"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Patterned Learning AI",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ775Codjmht--KvEAjOrA-wSTocct7jOgsqnDZ&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "-TNNtY9KwHQAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Engineer, Database (Entry Level)",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-engineer-database-entry-level-at-patterned-learning-ai-3639805158",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5576,
        "job_description": "REMOTE (US/Canada Residing people only, with work permit) Patterned Learning – Python Engineer, Database (Entry Level) , FULL-TIME, Salary $60K - $70K a year & minimum 1+ years of work experience.\n\nAbout us: The Future of AI is Patterned, a stealth-mode technology startup. Top investors include Sequoia and Anderson Horowitz, founders from Google, DeepMind, and NASA and we’re hiring for almost everything!\n\nThe worldwide data management software market is massive (IDC forecasts it to be $138 billion by 2026!). At Patterned Learning we are transforming industries and empowering developers to build amazing apps that people use every day. We are the leading modern data platform and the first database provider to IPO in over 20 years. Join our team and be at the forefront of innovation and creativity.\n\nThe Database Experience Team builds the libraries and tools that developers use day-to-day working with Patterned Learning. Our mission is to increase developer adoption and satisfaction by providing a reliable, enjoyable interface for developers and other end-users.\n\nOur department is responsible for maintaining official drivers and various other Patterned Learning-related libraries in 12 different programming languages. Our engineers are typically specialists in a particular programming language, but are capable of contributing to projects in other languages as well.\n\nFor this role, we're looking for someone who will enjoy designing, writing, and supporting open source libraries for Python developers that use Patterned Learning.\n\nYou Might Be Right For This Role If You\n• Have substantial experience writing high-quality software in Python\n• Have an interest in learning and staying up-to-date with Python ecosystem trends and best practices and incorporating them into your work\n• Want to, or already do, participate in open source software development and communities, both online via e.g. GitHub and optionally through conferences and speaking engagements\n• Communicate well, internally and externally, both verbally and in writing\n• Enjoy collaborating with teammates, and mentoring junior engineers and interns\n• Are self-motivated, organized, and have strong time management skills\n\nYou'll Be On The Team Responsible For\n• Writing and maintaining open source specifications defining common behavior and APIs shared across all of our drivers\n• Investigating bugs and support requests from commercial customers, open source users, and internal users for the libraries our team maintains\n• Working with our Product and Server teams on designs and specifications for new user-facing Patterned Learning features\n\nSuccess In This Role Means\n• Within one month, you will understand the high-level architecture of the drivers and how Patterned Learning works, and will have completed a few small bug fixes and/or feature tickets\n• Within three months, you will be contributing effectively day-to-day, fixing bugs, implementing features, investigating and responding to open source user and customer issues, and reviewing your peers' code\n• Within six months, you'll have implemented major, planned new features, contributed to our common driver specifications, and will be collaborating with the Product team to help craft our roadmap\n• Within twelve months, you'll have significantly improved the quality, performance and maintainability of our codebase, and will be taking the lead in designing and specifying major new features\n\nSpecial Benefits You Will Love\n• Flexible vacation, paid holidays, and paid sick days\n• 401(k) with up to 2% employer match\n• Health, vision, and dental insurance\n\nSchedule: 8 hour shift, Monday to Friday , Time: Flexible, Job Type: Full-time.\n\nNote: Freshers are highly encouraged to apply.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1687181208,
        "job_posted_at_datetime_utc": "2023-06-19T13:26:48.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": [
            "paid_time_off",
            "health_insurance",
            "dental_coverage",
            "retirement_savings"
        ],
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=-TNNtY9KwHQAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-12-16T13:26:49.000Z",
        "job_offer_expiration_timestamp": 1702733209,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Have substantial experience writing high-quality software in Python",
                "Have an interest in learning and staying up-to-date with Python ecosystem trends and best practices and incorporating them into your work",
                "Want to, or already do, participate in open source software development and communities, both online via e.g"
            ],
            "Responsibilities": [
                "GitHub and optionally through conferences and speaking engagements",
                "Communicate well, internally and externally, both verbally and in writing",
                "Enjoy collaborating with teammates, and mentoring junior engineers and interns",
                "Are self-motivated, organized, and have strong time management skills",
                "You'll Be On The Team Responsible For",
                "Writing and maintaining open source specifications defining common behavior and APIs shared across all of our drivers",
                "Investigating bugs and support requests from commercial customers, open source users, and internal users for the libraries our team maintains",
                "Working with our Product and Server teams on designs and specifications for new user-facing Patterned Learning features",
                "Within three months, you will be contributing effectively day-to-day, fixing bugs, implementing features, investigating and responding to open source user and customer issues, and reviewing your peers' code",
                "Within six months, you'll have implemented major, planned new features, contributed to our common driver specifications, and will be collaborating with the Product team to help craft our roadmap",
                "Within twelve months, you'll have significantly improved the quality, performance and maintainability of our codebase, and will be taking the lead in designing and specifying major new features"
            ],
            "Benefits": [
                "Flexible vacation, paid holidays, and paid sick days",
                "401(k) with up to 2% employer match",
                "Health, vision, and dental insurance"
            ]
        },
        "job_job_title": "Engineer",
        "job_posting_language": "en",
        "job_onet_soc": "15114100",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Dice",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
        "employer_website": null,
        "employer_company_type": "Information",
        "job_publisher": "LinkedIn",
        "job_id": "4jzwBa4dk6gAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Urgent Hiring // Python Developer // Full Time // Tampa, FL/New Jersey/Dallas/Remote in EST",
        "job_apply_link": "https://www.linkedin.com/jobs/view/urgent-hiring-python-developer-full-time-tampa-fl-new-jersey-dallas-remote-in-est-at-dice-3639177862",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5631,
        "job_description": "Hello,\n\nHope you are doing well. I am Sonali Dash, from Clps Global. I have a requirement for the position Python Developer.\n\nRole: Python Developer\n\nLocation: Tampa, FL/New Jersey/Dallas/Remote in EST\n\nJob Type: Full Time only\n\nSummary:\n\nWe are seeking a Python Developer who has over 6 years working with Python, Django on linux environments professionally, previous experience designing and building APIs using python, and someone who has the experience of leading a project/product design from the back end.\n\nResponsibilities:\n• Design and implement RESTful API's using Python in Django on linux environments.\n• Develop multithreaded solutions\n• Work with telecom related products such as netbox, itential, ansible\n• Support existing software products, applications and interfaces as necessary.\n• Evaluate emerging technologies, open source libraries and provide recommendations.\n• Support testing process and troubleshooting issues and resolving them.\n• Participating in architectural design sessions and product discussions.\n• Work collaboratively to provide scalable solutions.\n• Working with Agile/SCRUM team setting, including cross-functional structures, and varying levels of management.\n• Ability to balance competing priorities in a very dynamic and fast-paced environment.\n• Excellent detail-oriented, problem solving skills and the ability to quickly learn and apply new concepts, principles and solutions.\n\nQualifications:\n• 6-10+ years of Python experience and microservices based architecture\n• 4 years experience with Django\n• 6 years experience on linux platforms and shell scripting.\n• 2 years experience with Ansible/YAML a plus\n• Experience with Netconf a plus\n• Experience in telecom network facing applications is a plus.\n• Experience using SNMP protocol and trap based processing.\n• Solid database skills in a relational database (i.e. PostgreSQL, Oracle, MySQL, etc)\n• Experience and in-depth knowledge with Linux-based development.\n• Strong communication skills.\n• Comfortable with JIRA, git, Jenkins and Agile\n• Experience with celery, supervisord, nginx is a plus\n• Experience with developing user authentication and authorization solutions and knowledge of security compliance.\n• Knowledge of event driven programming in Python.\n• Experience with Test Driven Development.\n• Minimum Bachelor’s degree in Computer science.\n\nThanks & Regards\n\nSonali Dash\n\nUS IT Recruiter - CLPS-US\n\nCLPS Inc.\n\nDirect No: +1\n\nNasdaq: CLPS",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1687078627,
        "job_posted_at_datetime_utc": "2023-06-18T08:57:07.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=4jzwBa4dk6gAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-07-18T08:57:07.000Z",
        "job_offer_expiration_timestamp": 1689670627,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 72,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "We are seeking a Python Developer who has over 6 years working with Python, Django on linux environments professionally, previous experience designing and building APIs using python, and someone who has the experience of leading a project/product design from the back end",
                "Excellent detail-oriented, problem solving skills and the ability to quickly learn and apply new concepts, principles and solutions",
                "6-10+ years of Python experience and microservices based architecture",
                "4 years experience with Django",
                "6 years experience on linux platforms and shell scripting",
                "Experience using SNMP protocol and trap based processing",
                "Solid database skills in a relational database (i.e",
                "PostgreSQL, Oracle, MySQL, etc)",
                "Experience and in-depth knowledge with Linux-based development",
                "Strong communication skills",
                "Comfortable with JIRA, git, Jenkins and Agile",
                "Experience with developing user authentication and authorization solutions and knowledge of security compliance",
                "Knowledge of event driven programming in Python",
                "Experience with Test Driven Development",
                "Minimum Bachelor’s degree in Computer science"
            ],
            "Responsibilities": [
                "Design and implement RESTful API's using Python in Django on linux environments",
                "Develop multithreaded solutions",
                "Work with telecom related products such as netbox, itential, ansible",
                "Support existing software products, applications and interfaces as necessary",
                "Evaluate emerging technologies, open source libraries and provide recommendations",
                "Support testing process and troubleshooting issues and resolving them",
                "Participating in architectural design sessions and product discussions",
                "Work collaboratively to provide scalable solutions",
                "Working with Agile/SCRUM team setting, including cross-functional structures, and varying levels of management"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "519130",
        "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals"
    },
    {
        "employer_name": "extend information systems inc.",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "WKRG Jobs",
        "job_id": "pFi9iDg70LEAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Looking for python Developer -Houston,TX- Full-time",
        "job_apply_link": "https://jobs.wkrg.com/jobs/looking-for-python-developer-houston-tx-full-time-houston-texas/1039314001-2/",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.524,
        "job_description": "Hi, Jobseekers,\n\nI hope you are doing well!\n\nWe have an opportunity for Python Developer with one of our clients for Houston, TX.\n\nPlease see the job details below and let me know if you would be interested in this role.\n\nIf interested, please send me a copy of your resume, contact details, availability, and a good time to connect with you.\n\nTitle: Python Developer\n\nLocation: Houston, TX\n\nTerms: Full-time\n\nJob Details\n\n5+ years' experience as Python developer.\n\nHands on experience in Django framework.\n\nStrong exposure and development experience using Time series data.\n\nRegression models (simple and more advanced techniques, linear and non-linear),\n\nTime series modelling\n\nStandard array of statistical software packages (Python, R, EViews, SAS)\n\nAzure fundamentals\n\nPower BI foundation level knowledge\n\nThanks & Regards\n\nMonika Singh\n\nExtend Information System Inc\n\nPhone:571-622-3980\n\nEmail: monika@\n\n44258 Mercure Circle, UNIT 102 A, Sterling VA, USA 20166",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1687051874,
        "job_posted_at_datetime_utc": "2023-06-18T01:31:14.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=pFi9iDg70LEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "5+ years' experience as Python developer",
                "Hands on experience in Django framework",
                "Strong exposure and development experience using Time series data",
                "Power BI foundation level knowledge"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "TEKtalent Inc",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhxlntGMOISu1Tba657UdwhWlr_ZYJyqavTXK5&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "LinkedIn",
        "job_id": "kabnyBYVk4QAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer ( Entry Level )",
        "job_apply_link": "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-tektalent-inc-3636499688",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5758,
        "job_description": "We are seeking a Python Developer (Entry Level) to become an integral part of our team! You will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1686948483,
        "job_posted_at_datetime_utc": "2023-06-16T20:48:03.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=kabnyBYVk4QAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-07-16T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1689465600,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": true,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 80000,
        "job_max_salary": 100000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "Previous experience in software development, computer engineering, or other related fields",
                "Knowledge of Java, Python, or other programming languages",
                "Familiarity with relational databases such as MySQL, Oracle, and SQL Server",
                "Deadline and detail-oriented",
                "Strong analytical and critical thinking skills"
            ],
            "Responsibilities": [
                "You will be responsible for creating and modifying computer application software or specialized utility programs",
                "Analyze user needs and develop software solutions",
                "Work with project manager or product owner to meet specification needs",
                "Recommend software upgrades to optimize operational efficiency",
                "Collaborate with other developers to design and optimize code",
                "Create flowcharts and user guides for new and existing programs",
                "Document all programming tasks and procedures",
                "Perform routine software maintenance"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "SynergisticIT",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5BSMIt7m2uiId_3142LNElhU-kvf9h48rIEOM&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Trabajo.org",
        "job_id": "TaQuveCK_4AAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Programmer",
        "job_apply_link": "https://us.trabajo.org/job-835-20230619-e089ba739d834eef192eca27a22e4e16",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.3854,
        "job_description": "Job Description\n\nSynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\n\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\n\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications and Background\nBachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\nMathematics or Statistics background\nSkills Required\n0 to 2 years of experience in Python development\nDeep understanding of the software development life cycle\nKnowledge of Linear Algebra, Statistics, and Mathematics concepts\nExcellent written and verbal communication skills\nTechnically inquisitive, self-learner, team player, and highly motivated\nStrong work ethics and creative problem-solving abilities\nPreferred Skills\nDeep Learning\nData visualization\nScala\nNLP\nDjango\nRoles and Responsibilities\n\ns an entry-level Python Developer, you need to perform the following duties:\nWrite server-side web application logic\nWrite scalable and effective codes in Python\n\nDevelop backend components to boost overall application's performance\nExecuting tests and fixing bugs in applications and software\nImplement data protection and security solutions\nConnect applications with third-party web services\nSupport frontend developers by integrating UI elements into Python applications\nBenefits\nCompetitive salary\nFlexible work schedule & part-time off\nE-verified\nH1B Filing\nNo relocation\nOn job technical support\nSkill Enhancement\nOpportunity to work with Fortune 500 Companies\nWho can apply?\n\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\n\nCandidate's Outcome :\n\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.\nSDL2017",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1687156561,
        "job_posted_at_datetime_utc": "2023-06-19T06:36:01.000Z",
        "job_city": "Texas City",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.383844,
        "job_longitude": -94.9027,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=TaQuveCK_4AAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-06-26T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1687737600,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
                "Mathematics or Statistics background",
                "0 to 2 years of experience in Python development",
                "Deep understanding of the software development life cycle",
                "Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
                "Excellent written and verbal communication skills",
                "Technically inquisitive, self-learner, team player, and highly motivated",
                "Strong work ethics and creative problem-solving abilities",
                "Support frontend developers by integrating UI elements into Python applications",
                "E-verified"
            ],
            "Responsibilities": [
                "Write server-side web application logic",
                "Write scalable and effective codes in Python",
                "Develop backend components to boost overall application's performance",
                "Executing tests and fixing bugs in applications and software",
                "Implement data protection and security solutions",
                "Connect applications with third-party web services"
            ],
            "Benefits": [
                "Competitive salary",
                "Flexible work schedule & part-time off"
            ]
        },
        "job_job_title": "Programmer",
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4"
    },
    {
        "employer_name": "Magnus Technology Solutions",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6jDxj9ijK5FI1q7aYX2LJr7YxTpzqyPhX_-tp&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "ZipRecruiter",
        "job_id": "Z99jk-IWulEAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Python Developer (Entry Level)",
        "job_apply_link": "https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-(Entry-Level)/-in-Dallas,TX?jid=fd404ba337347616",
        "job_apply_is_direct": true,
        "job_apply_quality_score": 0.7235,
        "job_description": "We are seeking a Python Developer (Entry Level) to become an integral part of our team! You will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills\n\nCompany DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #QA_Testing, #QA_Automation, #Manual_Testing #Dotnet, #java, #j2ee, #java_UI, #Angular, #React, #Python, #DevOps, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.",
        "job_is_remote": true,
        "job_posted_at_timestamp": 1686946775,
        "job_posted_at_datetime_utc": "2023-06-16T20:19:35.000Z",
        "job_city": "Dallas",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 32.776665,
        "job_longitude": -96.79699,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Z99jk-IWulEAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-07-19T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1689724800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 80000,
        "job_max_salary": 100000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "Previous experience in software development, computer engineering, or other related fields",
                "Knowledge of Java, Python, or other programming languages",
                "Familiarity with relational databases such as MySQL, Oracle, and SQL Server",
                "Deadline and detail-oriented",
                "Strong analytical and critical thinking skills",
                "Company DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA"
            ],
            "Responsibilities": [
                "You will be responsible for creating and modifying computer application software or specialized utility programs",
                "Analyze user needs and develop software solutions",
                "Work with project manager or product owner to meet specification needs",
                "Recommend software upgrades to optimize operational efficiency",
                "Collaborate with other developers to design and optimize code",
                "Create flowcharts and user guides for new and existing programs",
                "Document all programming tasks and procedures",
                "Perform routine software maintenance"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_occupational_categories": [
            "15-1132.00: Software Developers, Applications"
        ]
    },
    {
        "employer_name": "Georgia It Inc",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Georgia_Tech_seal.svg/1200px-Georgia_Tech_seal.svg.png",
        "employer_website": "https://www.gatech.edu",
        "employer_company_type": "Education",
        "job_publisher": "Sercanto",
        "job_id": "0YRwUj5IBuwAAAAAAAAAAA==",
        "job_employment_type": "CONTRACTOR",
        "job_title": "Hiring Immediately Python Developer  Austin TX",
        "job_apply_link": "https://us.sercanto.com/detail/a/hiring-immediately-python-developer-austin-tx_austin_2683729578",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.5131,
        "job_description": "Python Developer Austin TX-Georgia IT Inc Job Description Job Title : Python Developer Job Location : Austin, TX Job Type : Contract US Citizen/ GC /EAD (H4/L2/TN) preferred- No 3rdPARTIES RESUME C2C ACCEPTED Job Description 5-10 years' experience of working as a Computer Software Engineer or Software Developer 3 -8 years of experience developing software in Python Development, writing code, and documenting functionality using Python Produce quality code from specifications and technical designs Knowledge AWS services including Lambda, Step Function, SQS and SNS, S 3 X Ray and API Gateway, Data Engineering, Kafka, Snowflake experience. Working knowledge of MongoDB or Amazon DocumentDB preferably with Python Experience designing high capacity applications and with test driven development Working knowledge of GitHub, agile processes, mono repo and Serverless a plus Experience in documenting requirements and specifications Close familiarity with software engineering tools, software development methodology and release processes Proficient in Atlassian tools such as Jira for work management, Confluence for design documentation, an d working through a sprint centric delivery process Good problem solving skills and creativity Good communication both written and verbal",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1687132800,
        "job_posted_at_datetime_utc": "2023-06-19T00:00:00.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=0YRwUj5IBuwAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": 60,
            "experience_mentioned": true,
            "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": false,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_naics_code": "61",
        "job_naics_name": "Education"
    },
    {
        "employer_name": "SynergisticIT",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "ZipRecruiter",
        "job_id": "64rI85Q7b4wAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "PYTHON DEVELOPER(ENTRY LEVEL)",
        "job_apply_link": "https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.6874,
        "job_description": "Job Description\n\nSynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications and Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scal\n• NLP\n• Django\nRoles and Responsibilities\ns an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1626998400,
        "job_posted_at_datetime_utc": "2021-07-23T00:00:00.000Z",
        "job_city": "Austin",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 30.267153,
        "job_longitude": -97.74306,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=64rI85Q7b4wAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-07-19T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1689724800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": true,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": true,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 65000,
        "job_max_salary": 140000,
        "job_salary_currency": "USD",
        "job_salary_period": "YEAR",
        "job_highlights": {
            "Qualifications": [
                "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
                "Mathematics or Statistics background",
                "0 to 2 years of experience in Python development",
                "Deep understanding of the software development life cycle",
                "Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
                "Excellent written and verbal communication skills",
                "Technically inquisitive, self-learner, team player, and highly motivated",
                "Strong work ethics and creative problem-solving abilities",
                "Support frontend developers by integrating UI elements into Python applications"
            ],
            "Responsibilities": [
                "Write server-side web application logic",
                "Write scalable and effective codes in Python",
                "Develop backend components to boost overall application's performance",
                "Executing tests and fixing bugs in applications and software",
                "Implement data protection and security solutions",
                "Connect applications with third-party web services"
            ],
            "Benefits": [
                "Competitive salary",
                "Flexible work schedule & part-time off",
                "No relocation",
                "On job technical support",
                "Opportunity to work with Fortune 500 Companies"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_occupational_categories": [
            "15-1132.00: Software Developers, Applications"
        ]
    },
    {
        "employer_name": "SynergisticIT",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "ZipRecruiter",
        "job_id": "fFunVwyb9l4AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Entry Level Python Developer",
        "job_apply_link": "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer/-in-Houston,TX?jid=b5db608a2de13d7e",
        "job_apply_is_direct": false,
        "job_apply_quality_score": 0.6874,
        "job_description": "Job Description\n\nAbout Us:\nSynergistic IT is a full-service staffing and placement firm servicing client in America for the past 12+ years. We are dedicated towards fulfilling the IT needs of our clients. From staffing to full implementation of projects we provide the highest quality IT Services. We Intend to deliver exceptional student outcome. We don't just help you secure a tech job but build a solid career in technology.\n\nJob Description:\n• Should know how to work in large verities of libraries, frameworks, and modules\n• Duck typing, string, tuple and Lambda knowledge required\n• Django Frame work required\n• Worked on Django model, CBV, Django CRUD operation\n\nSkills Required-\n• Knowledge of Python web frameworks and event-driven programming in Python.\n• Basic understanding of front-end technologies.\n• High attention to detail.\n• Excellent communication and problem-solving skills.\n• Proficient understanding of code versioning tools\n• Know the classes of SCALA, Traits of SCALA, and Collection of SCALA\n\nEducation Requirement: -\nBachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering.\n\nBenefits:\n• On Job Technical support\n• E- verified\n• Help to get H1B Employer.\n• Full time position\n\nCandidate who are missing the required skills, might be provided an option to enhance their skills, so that they can also apply for the role and can make a career in IT industry.\n\nIf you do respond via e-mail, please include a daytime phone number so that we can reach you. In considering candidates, time is of the essence, so please respond ASAP. Thank you",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1670227200,
        "job_posted_at_datetime_utc": "2022-12-05T08:00:00.000Z",
        "job_city": "Houston",
        "job_state": "TX",
        "job_country": "US",
        "job_latitude": 29.760427,
        "job_longitude": -95.369804,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=fFunVwyb9l4AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-07-19T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1689724800,
        "job_required_experience": {
            "no_experience_required": false,
            "required_experience_in_months": null,
            "experience_mentioned": false,
            "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
            "postgraduate_degree": false,
            "professional_certification": false,
            "high_school": false,
            "associates_degree": false,
            "bachelors_degree": false,
            "degree_mentioned": true,
            "degree_preferred": false,
            "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {
            "Qualifications": [
                "Knowledge of Python web frameworks and event-driven programming in Python",
                "Basic understanding of front-end technologies",
                "High attention to detail",
                "Excellent communication and problem-solving skills",
                "Proficient understanding of code versioning tools",
                "Know the classes of SCALA, Traits of SCALA, and Collection of SCALA",
                "Bachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering"
            ],
            "Responsibilities": [
                "Django Frame work required",
                "Worked on Django model, CBV, Django CRUD operation"
            ],
            "Benefits": [
                "On Job Technical support",
                "Full time position"
            ]
        },
        "job_job_title": null,
        "job_posting_language": "en",
        "job_onet_soc": "15113200",
        "job_onet_job_zone": "4",
        "job_occupational_categories": [
            "15-1132.00: Software Developers, Applications"
        ]
    }
]

export default dummyData